import os
import json
from litellm import completion

class ChefBot:
    def __init__(self, model="gemini/gemini-pro", api_key=None):
        self.model = model
        self.api_key = api_key or os.environ.get("GEMINI_API_KEY") or os.environ.get("OPENAI_API_KEY") or "API_HERE"
        self.context = self._load_context()

    def _load_context(self):
        """Loads the ingredients/recipe from the JSON file generated by user_to_JSON.py"""
        try:
            file_path = os.path.join(os.path.dirname(__file__), "ingredients.json")
            if not os.path.exists(file_path):
                return None
            with open(file_path, "r") as f:
                return json.load(f)
        except Exception as e:
            print(f"Error loading context: {e}")
            return None

    def chat(self, user_question):
        """
        Answers user questions based on the loaded recipe context.
        """
        if self.api_key == "API_HERE":
            return "Please set your API key to chat with the Chef."

        if not self.context:
            return "I don't have a recipe loaded yet. Please plan a meal first!"

        system_prompt = f"""
        You are a generic professional teaching chef.
        You are helping a user cook the following dish: {self.context.get('dish', 'Unknown Dish')}.
        
        Here is the full recipe context:
        {json.dumps(self.context, indent=2)}

        Your goal is to answer the user's questions about the cooking process, ingredients, or techniques.
        Be encouraging, helpful, and concise.
        """

        try:
            response = completion(
                model=self.model,
                api_key=self.api_key,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_question}
                ]
            )
            return response.choices[0].message.content

        except Exception as e:
            return f"Chef Error: {e}"

if __name__ == "__main__":
    # Example Usage
    chef = ChefBot()
    
    # We simulate a conversation
    print("User: How exactly do I brown the beef?")
    print("Chef:", chef.chat("How exactly do I brown the beef?"))
